"""
Standalone report runner for formula date × ET breaks.

Core logic lives in utils.formula_break (also used by step 17).

Usage (repo root):
  python analysis/formula_et_date_break/analyze_formula_breaks.py
"""
from __future__ import annotations

import argparse
import csv
import json
import warnings
from collections import defaultdict
from pathlib import Path

import pandas as pd
import pyodbc

from utils.formula_break import (
    SLOT_META,
    build_collapsed_breaks,
    expand_breaks_to_property_targets,
)

warnings.filterwarnings("ignore", category=UserWarning)

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = Path(__file__).resolve().parent / "out"


def write_csv(path: Path, rows: list[dict], fieldnames: list[str]):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k) for k in fieldnames})


def write_summary_md(path: Path, break_rows, raw_note, stats, expand_stats):
    lines = [
        "# Formula break report (date × employment type)\n",
        "Generated by `analysis/formula_et_date_break/analyze_formula_breaks.py`.\n",
        "## Summary\n",
        f"- Collapsed break rows (factor×from-month×slot): **{len(break_rows)}**",
        f"- Property targets after ET expand: **{expand_stats.get('targets', 0)}**",
        f"- Skipped trivial-zero slots: **{expand_stats.get('skipped_zero', 0)}**",
        f"- {raw_note}",
        "",
        "## Slot legend\n",
        "| Slot | Label | Source ET IDs | Notes |",
        "|------|-------|---------------|-------|",
    ]
    for code, meta in SLOT_META.items():
        ets = ", ".join(str(x) for x in meta["source_et_ids"]) or "—"
        lines.append(f"| {code} | {meta['label']} | {ets} | {meta['notes']} |")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def ensure_report_table(dest_cursor):
    dest_cursor.execute(
        """
        IF OBJECT_ID('master.dbo.StatuteFactorFormulaBreakReport') IS NOT NULL
            DROP TABLE master.dbo.StatuteFactorFormulaBreakReport;

        CREATE TABLE master.dbo.StatuteFactorFormulaBreakReport (
            ReportRowID INT IDENTITY(1,1) PRIMARY KEY,
            SourcePayrollFactorID INT NOT NULL,
            DestStatuteFactorID BIGINT NULL,
            FactorName NVARCHAR(400) NULL,
            FieldName NVARCHAR(200) NULL,
            SourceKind NVARCHAR(80) NULL,
            SourceBackFormulaID INT NULL,
            SourceMonthID INT NULL,
            EffectiveFromMonth INT NULL,
            EffectiveToMonth INT NULL,
            Dispatcher NVARCHAR(80) NULL,
            SlotCode NVARCHAR(10) NULL,
            SlotLabel NVARCHAR(200) NULL,
            SourceEmploymentTypeIDs NVARCHAR(200) NULL,
            DestEmploymentTypeIDs NVARCHAR(200) NULL,
            OutputExpr NVARCHAR(MAX) NULL,
            IsTrivialZero BIT NOT NULL DEFAULT 0,
            OuterWrapper NVARCHAR(MAX) NULL,
            ParseStatus NVARCHAR(80) NULL,
            Notes NVARCHAR(1000) NULL,
            RawFormula NVARCHAR(MAX) NULL,
            GeneratedAt DATETIME NOT NULL DEFAULT GETDATE()
        );
        """
    )
    dest_cursor.commit()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--no-db-table", action="store_true")
    args = ap.parse_args()
    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    cfg = json.load(open(ROOT / "config.json", encoding="utf-8"))
    src = pyodbc.connect(cfg["source_conn"])
    dst = pyodbc.connect(cfg["dest_conn"])

    mapped = pd.read_sql(
        "SELECT SourcePayrollFactorID, DestStatuteFactorID "
        "FROM master.dbo.StatuteFactorMigrationMapping",
        dst,
    )
    factor_ids = [int(x) for x in mapped["SourcePayrollFactorID"].tolist()]
    dest_by_src = {
        int(r["SourcePayrollFactorID"]): int(r["DestStatuteFactorID"])
        for _, r in mapped.iterrows()
    }

    print("Building collapsed formula breaks...")
    breaks, et_map = build_collapsed_breaks(src, dst, factor_ids)
    for r in breaks:
        r["DestStatuteFactorID"] = dest_by_src.get(int(r["SourcePayrollFactorID"]))

    targets, expand_stats = expand_breaks_to_property_targets(breaks, et_map)
    print(f"  breaks={len(breaks)} property_targets={expand_stats['targets']}")

    fields = [
        "SourcePayrollFactorID", "DestStatuteFactorID", "FactorName", "FieldName",
        "SourceKind", "SourceBackFormulaID", "SourceMonthID",
        "EffectiveFromMonth", "EffectiveToMonth", "dispatcher",
        "SlotCode", "SlotLabel", "SourceEmploymentTypeIDs", "DestEmploymentTypeIDs",
        "OutputExpr", "IsTrivialZero", "outer_wrapper", "parse_status", "notes",
        "SourceMonthIDsCovered", "FormulaSql",
    ]
    write_csv(out_dir / "formula_breaks.csv", breaks, fields)

    tfields = [
        "SourcePayrollFactorID", "EffectiveFromMonth", "EffectiveToMonth",
        "DestEmploymentTypeID", "SlotCode", "SlotLabel", "OutputExpr",
        "IsTrivialZero", "dispatcher", "SourceBackFormulaID", "SourceKind",
        "FormulaSql",
    ]
    write_csv(out_dir / "formula_property_targets.csv", targets, tfields)
    write_summary_md(
        out_dir / "formula_breaks_summary.md",
        breaks,
        f"Mapped factors analyzed: {len(factor_ids)}",
        {},
        expand_stats,
    )

    if not args.no_db_table:
        print("Writing master.dbo.StatuteFactorFormulaBreakReport...")
        cur = dst.cursor()
        ensure_report_table(cur)
        sql = """
            INSERT INTO master.dbo.StatuteFactorFormulaBreakReport (
                SourcePayrollFactorID, DestStatuteFactorID, FactorName, FieldName,
                SourceKind, SourceBackFormulaID, SourceMonthID,
                EffectiveFromMonth, EffectiveToMonth, Dispatcher, SlotCode, SlotLabel,
                SourceEmploymentTypeIDs, DestEmploymentTypeIDs, OutputExpr, IsTrivialZero,
                OuterWrapper, ParseStatus, Notes, RawFormula
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """
        batch = []
        for r in breaks:
            batch.append(
                (
                    r.get("SourcePayrollFactorID"),
                    r.get("DestStatuteFactorID"),
                    r.get("FactorName"),
                    r.get("FieldName"),
                    r.get("SourceKind"),
                    r.get("SourceBackFormulaID"),
                    r.get("SourceMonthID"),
                    r.get("EffectiveFromMonth"),
                    r.get("EffectiveToMonth"),
                    r.get("dispatcher"),
                    r.get("SlotCode"),
                    r.get("SlotLabel"),
                    r.get("SourceEmploymentTypeIDs"),
                    r.get("DestEmploymentTypeIDs"),
                    r.get("OutputExpr"),
                    1 if r.get("IsTrivialZero") else 0,
                    r.get("outer_wrapper"),
                    r.get("parse_status"),
                    (r.get("notes") or "")[:1000],
                    r.get("FormulaSql"),
                )
            )
            if len(batch) >= 200:
                cur.executemany(sql, batch)
                batch = []
        if batch:
            cur.executemany(sql, batch)
        cur.commit()
        print(f"  inserted {len(breaks)} rows")

    print(f"Done. Outputs in: {out_dir}")
    src.close()
    dst.close()


if __name__ == "__main__":
    main()
